version: '3'
services:
  web:
    container_name: Apache-with-PHP
    image: php:apache
    ports:
      - "14080:80"
      - "14443:443"
    restart: unless-stopped
    volumes:
      - /var/www/docker/clever.bicko.tech/html/:/var/www/html/
      - /var/www/docker/clever.bicko.tech/logs/:/var/log/apache2/
